version: '3.4'
volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "MyElectricalShopDb"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    container_name: mydatabase

  myelectricalshop.web.api:
    image: myelectricalshopwebapi
    build:
      context: .
      dockerfile: MyElectricalShop/MyElectricalShopWeb.Api/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Docker
       - ConnectionStrings__MyElectricalShopContext=Host=host.docker.internal;Port=5432;Database=MyElectricalShopDb;User Id=postgres;Password=password;Timeout=15;
    container_name: myshop
    ports:
      - "5555:80"

  myelectricalshop.identity.web.api:
    image: myelectricalshopidentitywebapi
    build:
      context: .
      dockerfile: Identity/MyElectricalShop.Identity.Web.Api/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Docker
       - ConnectionStrings__IdentityContext=Host=host.docker.internal;Port=5432;Database=IdentityDb;User Id=postgres;Password=password;Timeout=15;
    container_name: myidentity
    ports:
      - "5566:80"

  proxyserver:
    image: nginx:1.21.1
    volumes:
        - ./Nginx/proxy:/etc/nginx/conf.d/
        - ./Nginx/proxy/nginx.conf:/etc/nginx/nginx.conf
    container_name: proxy
    ports:
        - "80:80"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
        - "5672:5672"
        - "15672:15672"

networks:
  default:
    name: my

